package com.pgi.logging.enums

enum class Interactions (val interaction: String) {
  SPLASH_SCREEN("Splash Screen"),
  ON_BOARDING("On Boarding"),
  WELCOME_TOUR("Welcome Tour"),
  WELCOME_TOUR_BLANK("Tour Blank View"),
  ABOUT("About"),
  ABOUT_WEB_VIEW("About Web View"),
  PERMISSIONS("OnBoard Permissions"),
  APP_LINK("FURL Link Handler"),
  GM4_GUEST_ROOM("GM4 Guest Room"),
  GM4_HOST_ROOM("GM4 Host Room"),
  HOME("Home Screen"),
  RECENTS("Recents"),
  SEARCH("Search"),
  SETTINGS("Settings"),
  UPDATE_NAME("Update Name"),
  GM5_MEETING_ROOM("GM5 Meeting Room"),
  ACTIVE_TALKER("Active Talker"),
  ADD_DIALOUT_NUMBER("Add Dialout Number"),
  AUDIO_SELECTION("Audio Selection"),
  AUDIO_SELECTION_PROGRESS("Audio Loading Shimmer"),
  CHAT("Chat"),
  DIALIN_SELECTION("DialIn Selection"),
  DIALIN("DialIn"),
  DIALIN_SEARCH("DialIn Search"),
  DIAL_OUT("Dial Out"),
  ENTER_URL_SEARCH("Enter URL Search"),
  PARTICIPANT_LIST("Participant List"),
  CONTENT_VIEW("Content View"),
  FEEDBACK("Feedback"),
  OVERFLOW_MENU("OVerflow Menu Dialog")
}