package com.pgi.logging.enums

enum class LogTags(val eventName: String) {
    APP_LAUNCH("APP_LAUNCH"),
    SIGN_IN("IDENTITY_SIGNIN"),
    TOKEN_REFRESH("IDENTITY_TOKENREFRESH"),
    SIGN_OUT("IDENTITY_SIGNOUT"),
    START_MEETING("ERROR_STARTINGMEETING"),
    JOIN_MEETING("ERROR_JOININGMEETING"),
    APP_LINK("FEATURE_FURLLINKHANDLER"),
    HELP("HELP"),
    VIEW("VIEW"),
    ERROR("ERROR"),
    AUDIO_CONNECT("AUDIO_CONNECT"),
    SCREEN_SHARE("SCREEN_SHARE"),
    FILE_PRESENTATION("FILE_PRESENTATION"),
    CHAT("CHAT"),
    EXIT_MEETING("EXIT_MEETING"),
    LEAVE_MEETING("LEAVE_MEETING"),
    AUDIO("audio")
}